#!/bin/bash

ALL=`docker run --help | grep -Po "\-\-(.+? )" | cut -c3-`


true > loader.go

echo "// This file is generated by genstub.sh" >> loader.go
echo "package main" >> loader.go

for o in $ALL; do
    mkdir -p opts/$o
    echo "import _ \"github.com/tg123/docker-tocmd/opts/$o\"" >> loader.go

    mod=opts/$o/mod.go

    # echo "// This file is generated by genstub.sh" > $mod
    cat <<EOL > $mod
// This file is generated by genstub.sh

package optvar

import (
	"github.com/tg123/docker-tocmd/opts"
	"github.com/docker/docker/api/types"
)

type stub struct {
	impl func (container types.ContainerJSON) string
}

var mod stub

func (s *stub) Generate(container types.ContainerJSON) string {
	if s.impl != nil {
		return s.impl(container)
	}

	return ""
}

func init(){
	optvar.AddOptVar(&mod)
}
EOL

done



