// This file is generated by genstub.sh

package optvar

import (
	"github.com/tg123/docker-tocmd/opts"
	"github.com/docker/docker/api/types"
)

type stub struct {
	impl func (container types.ContainerJSON) string
}

var mod stub

func (s *stub) Generate(container types.ContainerJSON) string {
	if s.impl != nil {
		return s.impl(container)
	}

	return ""
}

func init(){
	optvar.AddOptVar(&mod)
}
